### DrDos's Alacritty config
[general]
import = [
  "~/.config/alacritty/solarized_light.toml",
  "~/.config/alacritty/local.toml"  # Local overrides
]
live_config_reload = true

[terminal]
osc52 = "CopyPaste"  # Allow TUI Apps to write to system clipboard

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
opacity = 1.0
dynamic_title = true
dynamic_padding = true
title = "Alacritty"
class = { general = "Alacritty", instance = "alacritty" }

[window.padding]
x = 8
y = 8

[mouse]
hide_when_typing = true

[font]
builtin_box_drawing = true

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Beam", blinking = "Off" }
thickness = 0.15

[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t‘’“”*=&?@#$%^;!/~+-"

[bell]
animation = "Linear"
duration = 100

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[hints]
alphabet = "asdfghjklqwertyuiopzxcvbnm"

[[hints.enabled]]
regex = "(~|/)[^\\s:]+"
command = { program = "bash", args = ["-lc", "emacs -nw -- {0}"] }
post_processing = true
mouse = { enabled = false }
binding = { key = "E", mods = "Control|Shift" }
